services:
  db:
    image: mysql:8.0
    container_name: dockerkosmetik_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: db_kosmetik
      MYSQL_USER: phpuser
      MYSQL_PASSWORD: phppassword
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
  web:
    build: .
    container_name: dockerkosmetik_fe
    ports:
      - "8080:80"
    environment:
      DB_HOST: db
      DB_USER: phpuser
      DB_PASSWORD: phppassword
      DB_NAME: db_kosmetik
    depends_on:
      - db
    volumes:
      - .:/var/www/html

volumes:
  db_data: {}
